# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

# Setup font
font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0

# No bells. Ever.
enable_audio_bell no
bell_on_tab no

# Default layout 
enabled_layouts tall:bias=40;full_size=1;mirrored=false

# Don't draw extra borders, but fade the inactive text a bit
active_border_color none
inactive_text_alpha 0.6

# tab_bar_edge top
tab_bar_style powerline


update_check_interval 24
startup_session default-session.conf
map ctrl+shift+q noop

# Open new split (window) with cmd+d retaining the cwd
map cmd+d new_window_with_cwd

# Open new tab with cmd+t
map cmd+t new_tab_with_cwd

# New split with default cwd
map cmd+shift+d new_window

# Switch between next and previous splits
map cmd+]        next_window
map cmd+[        previous_window

# Clear the terminal screen
map cmd+k combine : clear_terminal scrollback active : send_text normal,application \x0c

# Jump to beginning and end of word
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

# Jump to beginning and end of line
map cmd+left send_text all \x01
map cmd+right send_text all \x05

# Map cmd + <num> to corresponding tabs
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# Changing font sizes
map cmd+equal    change_font_size all +2.0
map cmd+minus    change_font_size all -2.0
map cmd+0        change_font_size all 0

# Mappings for vim
map cmd+b send_text normal,application \x02
map cmd+f send_text normal,application *
map cmd+j send_text normal,application \n
map cmd+p send_text normal,application \x10
# map cmd+s send_text normal,application ,W 
# map cmd+/ send_text normal,application

#: Color scheme 
foreground   #e6e6dc
background   #002635

# black
color0       #00384d
color8       #517f8d

# red
color1       #c43061
color9       #ff5a67

# green
color2       #7fc06e
color10      #9cf087

# yellow
color3       #f08e48
color11      #ffcc1b

# blue
color4       #1c8db2
color12      #7eb2dd

# magenta
color5       #c694ff
color13      #fb94ff

# cyan
color6       #00cccc
color14      #00ffff

# white
color7       #77929e
color15      #b7cff9
